# Generated by Django 6.0.6 on 2026-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_analyses', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Input Text')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, verbose_name='Predicted Sentiment')),
                ('confidence', models.FloatField(verbose_name='Confidence Score (%)')),
                ('positive_score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'db_table': 'sentiment_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
